/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/earth.glb 
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-f7a76c63ff1846afb2d606e5c8369c15
Title: Earth
*/

import { useGLTF } from '@react-three/drei';
export const Earth = (props) => {
  const { nodes, materials } = useGLTF('/earth.glb');
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials['Scene_-_Root']}
        scale={1.128}
      />
    </group>
  );
};

useGLTF.preload('/earth.glb');
